(function () {
  window.PEOPLE_PLACES_TOURS = [
    {
      slug: 'just-go-ghana',
      title: 'Just Go Ghana',
      homeTitle: 'Just Go Ghana - 8 Days',
      detailUrl: 'just-go-ghana.html',
      price: '$3,000',
      priceUnit: 'Per Person',
      duration: '8 Days / 7 Nights',
      groupSize: '1–12 (larger by arrangement)',
      location: 'Accra, Ghana',
      destination: 'accra',
      categories: ['multi-day', 'culture', 'adventure', 'nature', 'relaxation'],
      vibes: ['Multi-Day', 'Culture', 'Adventure'],
      badge: 'Featured',
      image: 'https://images.unsplash.com/photo-1740447605529-67cf861116ba?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1740447605529-67cf861116ba?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Just Go Ghana 8 day tour',
      description: 'Eight days across Ghana: batik and drumming in Accra, the Aburi hills and Tetteh Quarshie\'s cocoa farm, Assin Manso and Cape Coast Castle, Shai Hills and a cruise at Akosombo, and a day at Safari Valley.',
      packageDescription: 'An immersive 8-day Ghana journey with culture, nature, heritage, accommodation, meals, local guides, and airport transfers handled for you.',
      commandSummary: 'Accra, Cape Coast, Kumasi, Volta Lake, culture and nature',
      homeFeatured: true,
      homeOrder: 1,
      packageOrder: 0
    },
    {
      slug: 'accra-city',
      title: 'Accra City Tour',
      detailUrl: 'accra-city-tour.html',
      price: '$110',
      priceUnit: 'Per Person',
      duration: 'Half Day',
      groupSize: '1-8 People',
      location: 'Accra',
      destination: 'accra',
      categories: ['culture'],
      vibes: ['Culture', 'History'],
      badge: 'Popular',
      image: 'https://images.unsplash.com/photo-1763301531293-c8ee26993927?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1763301531293-c8ee26993927?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Accra City Tour',
      description: 'Drumming and craft at the Art Centre, then Independence Square, the Kwame Nkrumah Memorial Park and the National Museum. Accra\'s story in a half day, told by someone who lives here.',
      packageDescription: 'Visit Makola Market, the National Museum, Kwame Nkrumah Mausoleum, and the historic Jamestown lighthouse in one epic half-day circuit.',
      commandSummary: 'Art Centre drumming, Independence Square, Nkrumah Park',
      packageOrder: 1
    },
    {
      slug: 'accra-food',
      title: 'Accra After Dark Food Tour',
      detailUrl: 'accra-food-tour.html',
      price: '$90',
      priceUnit: 'Per Person',
      duration: 'Evening',
      groupSize: '3-8 People',
      location: 'Accra',
      destination: 'accra',
      categories: ['food', 'culture'],
      vibes: ['Foodie', 'Nightlife'],
      badge: 'Foodie',
      image: 'https://images.unsplash.com/photo-1672537627568-3530c83694f6?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1672537627568-3530c83694f6?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Accra food and nightlife tour',
      description: 'Eat your way through Accra after dark: waakye stalls, kelewele vendors, rooftop bars, chop bars, and night markets.',
      packageDescription: 'From waakye stalls to kelewele vendors and rooftop bars - taste Accra\'s legendary food scene as the city lights up at night.',
      commandSummary: 'Waakye, kelewele, chop bars, night markets',
      packageOrder: 3
    },
    {
      slug: 'cape-coast',
      title: 'Cape Coast Ancestral Tour',
      detailUrl: 'cape-coast-tour.html',
      price: '$160',
      priceUnit: 'Per Person',
      duration: 'Full Day',
      groupSize: '1-12 People',
      location: 'Assin Manso, Cape Coast, Elmina',
      destination: 'cape-coast',
      categories: ['culture', 'heritage'],
      vibes: ['Heritage', 'History'],
      badge: 'Best Seller',
      image: 'https://images.unsplash.com/photo-1712700853174-f555aeb2c80d?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1712700853174-f555aeb2c80d?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Cape Coast Castle ancestral tour',
      description: 'A journey of remembrance that begins at the Assin Manso Ancestral Slave River, where enslaved Africans took their last bath on African soil, and continues to Cape Coast Castle, its dungeons and the Door of No Return. The day ends with lunch overlooking the Atlantic at Elmina or Cape Coast.',
      packageDescription: 'Cape Coast Castle, its dungeons and the Door of No Return, where captured Africans were held before being forced onto ships. Your host gives you the history before you go in, and room afterwards.',
      commandSummary: 'Assin Manso, Cape Coast Castle, Door of No Return',
      homeFeatured: true,
      homeOrder: 2,
      packageOrder: 4
    },
    {
      slug: 'kumasi',
      title: 'Kumasi Cultural Tour',
      detailUrl: 'kumasi-tour.html',
      price: '$250',
      priceUnit: 'Per Person',
      duration: '1 Day',
      groupSize: '1-10 People',
      location: 'Adanwomase, Ntonso, Kumasi',
      destination: 'kumasi',
      categories: ['culture'],
      vibes: ['Culture', 'Craft'],
      badge: 'Cultural',
      image: 'https://images.unsplash.com/photo-1776153380872-108ba14dc63d?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1776153380872-108ba14dc63d?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Kumasi Ashanti cultural tour',
      description: 'The Ashanti heartland in a day: hand-woven kente at Adanwomase, Adinkra stamping at Ntonso where you make your own sash, and Manhyia Palace, home of the Asantehene until 1974. By road, or by domestic flight for a shorter day.',
      packageDescription: 'The Ashanti Kingdom\'s beating heart - Manhyia Palace, Kejetia Market, Kente weaving villages, and the rich traditions of the Ashanti people.',
      commandSummary: 'Kente weaving, Adinkra stamping, Manhyia Palace',
      packageOrder: 6
    },
    {
      slug: 'ada-foah',
      title: 'Ada Day Tour',
      detailUrl: 'ada-tour.html',
      price: '$150',
      priceUnit: 'Per Person',
      duration: 'Full Day',
      groupSize: '1-15 People',
      location: 'Vume, Ada',
      destination: 'ada-foah',
      categories: ['relaxation', 'nature'],
      vibes: ['Beach', 'Nature'],
      badge: 'Beach',
      image: 'https://images.unsplash.com/photo-1649519764616-bacf4a942730?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1649519764616-bacf4a942730?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Ada Foah beach and canoe safari',
      description: 'Make your own piece at a pottery workshop in Vume, then board a boat through the waterways of Ada to Coconut Island for fresh coconut, Crocodile Island, and Rum Island\'s family sugar-cane distillery.',
      packageDescription: 'Where the Volta River meets the Atlantic. Glide through mangroves, spot river birds, and unwind on one of Ghana\'s most beautiful beaches.',
      commandSummary: 'Vume pottery, island hopping, Coconut and Crocodile Islands',
      homeFeatured: true,
      homeOrder: 4,
      packageOrder: 8
    },
    {
      slug: 'quad-bike',
      title: 'Quadbike & Waterfalls',
      detailUrl: 'quad-bike-tour.html',
      price: '$130',
      priceUnit: 'Per Person',
      duration: 'Full Day',
      groupSize: '1-8 People',
      location: 'Eastern Region, Peduase',
      destination: 'volta',
      categories: ['adventure', 'nature'],
      vibes: ['Adventure', 'Thrills'],
      badge: 'Thrill',
      image: 'https://images.unsplash.com/photo-1636389396809-c3ab57b60d93?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1636389396809-c3ab57b60d93?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Quad bike tour and waterfalls in Ghana',
      description: 'Off-road quad biking through the Eastern Region, then a waterfall to wash the dust off. Lunch at Peduase Valley Resort with its mini zoo and the quiet after a loud morning.',
      packageDescription: 'Rip through forest trails on quad bikes, then cool off under the powerful Boti or Wli waterfalls. Ghana\'s wildest day out.',
      commandSummary: 'Quad biking, waterfalls, Peduase Valley Resort',
      packageOrder: 9
    },
    {
      slug: 'volta',
      title: 'Volta Day Tour',
      homeTitle: 'Volta River & Wli Falls',
      detailUrl: 'volta-tour.html',
      price: '$180',
      priceUnit: 'Per Person',
      duration: 'Full Day',
      groupSize: '1-12 People',
      location: 'Atimpoku, Amedzofe, Tafi Atome, Wli',
      destination: 'volta',
      categories: ['nature', 'adventure'],
      vibes: ['Adventure', 'Nature'],
      badge: 'Nature',
      image: 'https://images.unsplash.com/photo-1649519764815-ec68b9e7c52a?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1636739969909-7ad906d3d18e?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Volta River and Wli Falls',
      description: 'A long day north-east: the Adomi Bridge at Atimpoku, a hike up Mount Gemi at Amedzofe, the monkeys at Tafi Atome, and finally Wli Waterfalls, the highest in West Africa, thirty minutes on foot from the road.',
      packageDescription: 'West Africa\'s highest waterfall is breathtaking. A guided jungle hike brings you through butterfly gardens and bat colonies to the roaring falls.',
      commandSummary: 'Adomi Bridge, Mount Gemi, monkey sanctuary, Wli Falls',
      packageOrder: 10
    },
    {
      slug: 'shai-hills',
      title: 'Shai Hills & Boat Cruise',
      homeTitle: 'Shai Hills Wildlife Reserve',
      detailUrl: 'shai-hills-tour.html',
      price: '$140',
      priceUnit: 'Per Person',
      duration: 'Full Day',
      groupSize: '1-10 People',
      location: 'Shai Hills, Akosombo',
      destination: 'accra',
      categories: ['adventure', 'nature'],
      vibes: ['Nature', 'Wildlife'],
      badge: 'Adventure',
      image: 'https://images.unsplash.com/photo-1590409110365-70d93eff6b4c?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1590409110365-70d93eff6b4c?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Shai Hills wildlife reserve',
      description: 'Wildlife reserve safari, baboon encounters, crocodile sightings, and a boat cruise on the Volta at Akosombo. One day, everything.',
      packageDescription: 'Wildlife reserve safari, baboon encounters, crocodile sightings, and a sunset boat cruise on the Volta River. One day, everything.',
      commandSummary: 'Wildlife reserve, baboons, Akosombo boat cruise',
      homeFeatured: true,
      homeOrder: 3,
      packageOrder: 11
    },
    {
      slug: 'aburi',
      title: 'Aburi Day Tour',
      detailUrl: 'aburi-tour.html',
      price: '$120',
      priceUnit: 'Per Person',
      duration: 'Full Day',
      groupSize: '1-15 People',
      location: 'Aburi, Peduase',
      destination: 'accra',
      categories: ['nature', 'relaxation'],
      vibes: ['Nature', 'Relaxation'],
      badge: 'Scenic',
      image: 'https://images.unsplash.com/photo-1636739970121-6eeb25262090?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1636739970121-6eeb25262090?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Aburi Botanical Gardens day tour',
      description: 'Cool air in the Aburi Botanical Gardens, then Tetteh Quarshie\'s farm where cocoa first took root in Ghana, and a waterfall to finish. Lunch at Peduase Valley Resort, where there is a small zoo to walk off the drive.',
      packageDescription: 'Escape the Accra heat to the lush Aburi Botanical Gardens in the hills. Cool air, towering trees, and panoramic views of the plains below.',
      commandSummary: 'Botanical gardens, Tetteh Quarshie cocoa farm, waterfall',
      packageOrder: 12
    },
    {
      slug: 'batik-workshop',
      title: 'Batik & Pottery Workshop',
      detailUrl: 'batik-workshop.html',
      price: '$120',
      priceUnit: 'Per Person',
      duration: '1 Day',
      groupSize: '1-8 People',
      location: 'Accra, Ghana',
      destination: 'accra',
      categories: ['culture', 'craft'],
      vibes: ['Craft', 'Workshop'],
      badge: 'Workshop',
      image: 'https://images.unsplash.com/photo-1552710307-537199cd41c0?auto=format&fit=crop&w=800&q=80&h=560',
      packageImage: 'https://images.unsplash.com/photo-1552710307-537199cd41c0?auto=format&fit=crop&w=800&q=80&h=550',
      alt: 'Batik and pottery workshop in Ghana',
      description: 'Learn batik fabric-making and pottery from master artisans, then take home a piece you made yourself.',
      packageDescription: 'Get hands-on with Ghana\'s craft traditions. Learn batik fabric-making and pottery from master artisans and take home a unique piece you made yourself.',
      commandSummary: 'Batik, pottery, artisan workshop',
      packageOrder: 14
    }
  ];
})();
